version: 2.1
jobs:
  walking-tracker:
    docker:
      - image: cimg/ruby:3.1.2
    steps:
      - add_ssh_keys:
          fingerprints:
            - $CI_FINGERPRINT
      - checkout
      - run: |
          bundle install
          bundle exec ruby ./get_steps.rb
          git config user.email $GIT_CONFIG_EMAIL
          git config user.name $GIT_CONFIG_USERNAME
          git config --global push.default current
          git add refresh
          git commit -m "update refresh token [skip ci]"
          git push --set-upstream origin
workflows:
  walking-tracker-workflow:
    triggers:
      - schedule:
          cron: "0 16 * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - walking-tracker
